### ISSUE TITLE
按照文档的操作后，通过 ADB 安装应用还是有弹窗，求指引

### ISSUE THREAD

**Issue by JIUJIUs** [tylinux/FuckOppoLimit#1]
![image](https://github.com/tylinux/FuckOppoLimit/assets/61548656/bc0fdad1-4d5a-4c1b-a2a4-8e0f2e85cb36)
![image](https://github.com/tylinux/FuckOppoLimit/assets/61548656/3d309463-e100-4dc6-a472-f2a1718df2c8)
![5b260df159043b528517c57581d8640](https://github.com/tylinux/FuckOppoLimit/assets/61548656/2c3ddf85-cbbd-4ba5-b8d7-4d738d97fc30)

**Comment by tylinux** [comment]
可能是新版本 ColorOS 逻辑有改动，之前测试都是在 Android 10 上进行的，我去了解一下。

**Comment by JIUJIUs** [comment]
> 可能是新版本 ColorOS 逻辑有改动，之前测试都是在 Android 10 上进行的，我去了解一下。

感谢回复！最近在做自动化相关，被这步卡住了！希望可以得到更新

**Comment by JIUJIUs** [comment]
> 可能是新版本 ColorOS 逻辑有改动，之前测试都是在 Android 10 上进行的，我去了解一下。

https://github.com/Nain57/Smart-AutoClicker

暂时用这个项目的【自动点击】曲线救国了~

**Comment by tylinux** [comment]
@JIUJIUs 更新啦，已经适配 ColorOS 12、13、14啦
